const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("ide", {
  selectWorkspace: () => ipcRenderer.invoke("workspace:select"),
  getWorkspace: () => ipcRenderer.invoke("workspace:get"),
  listDir: (targetPath) => ipcRenderer.invoke("fs:list", targetPath),
  readFile: (targetPath) => ipcRenderer.invoke("fs:readFile", targetPath),
  writeFile: (payload) => ipcRenderer.invoke("fs:writeFile", payload),
  createFile: (payload) => ipcRenderer.invoke("fs:createFile", payload),
  createDir: (payload) => ipcRenderer.invoke("fs:createDir", payload),
  deletePath: (payload) => ipcRenderer.invoke("fs:delete", payload),
  renamePath: (payload) => ipcRenderer.invoke("fs:rename", payload),
  pathExists: (path) => ipcRenderer.invoke("fs:exists", path),
  revealPath: (path) => ipcRenderer.invoke("fs:revealPath", path),
  refreshFileTree: () => ipcRenderer.invoke("fs:refreshTree"),
  search: (query) => ipcRenderer.invoke("search:run", query),
  startPlanning: (prompt) => ipcRenderer.invoke("planning:start", prompt),
  updateAnswer: (payload) => ipcRenderer.invoke("planning:answer", payload),
  listEvents: (sessionId) => ipcRenderer.invoke("events:list", sessionId),
  clearLogs: () => ipcRenderer.invoke("logs:clear"),
  runCommand: (payload) => ipcRenderer.invoke("run:command", payload),
  listTasks: (sessionId) => ipcRenderer.invoke("tasks:list", sessionId),
  startTerminal: () => ipcRenderer.invoke("terminal:start"),
  createTerminal: (payload) => ipcRenderer.invoke("terminal:create", payload),
  listTerminals: () => ipcRenderer.invoke("terminal:list"),
  renameTerminal: (payload) => ipcRenderer.invoke("terminal:rename", payload),
  killTerminal: (payload) => ipcRenderer.invoke("terminal:kill", payload),
  getAvailableShells: () => ipcRenderer.invoke("terminal:getShells"),
  sendTerminalInput: (payload) => ipcRenderer.send("terminal:input", payload),
  resizeTerminal: (payload) => ipcRenderer.send("terminal:resize", payload),
  disposeTerminal: (payload) => ipcRenderer.send("terminal:dispose", payload),
  onTerminalData: (callback) => {
    const listener = (_event, data) => callback(data);
    ipcRenderer.on("terminal:data", listener);
    return () => {
      ipcRenderer.removeListener("terminal:data", listener);
    };
  },
  gitStatus: (workspace) => ipcRenderer.invoke("git:status", workspace),
  gitStage: (payload) => ipcRenderer.invoke("git:stage", payload),
  gitStageAll: (workspace) => ipcRenderer.invoke("git:stage-all", workspace),
  gitUnstageAll: (workspace) => ipcRenderer.invoke("git:unstage-all", workspace),
  gitUnstage: (payload) => ipcRenderer.invoke("git:unstage", payload),
  gitDiscard: (payload) => ipcRenderer.invoke("git:discard", payload),
  gitCommit: (payload) => ipcRenderer.invoke("git:commit", payload),
  gitDiff: (payload) => ipcRenderer.invoke("git:diff", payload),
  gitStagedDiff: (workspace) => ipcRenderer.invoke("git:staged-diff", workspace),
  gitLog: (payload) => ipcRenderer.invoke("git:log", payload),
  gitBranches: () => ipcRenderer.invoke("git:branches"),
  gitRemoteBranches: () => ipcRenderer.invoke("git:remote-branches"),
  gitCreateBranch: (payload) => ipcRenderer.invoke("git:branch-create", payload),
  gitDeleteBranch: (payload) => ipcRenderer.invoke("git:branch-delete", payload),
  gitRenameBranch: (payload) => ipcRenderer.invoke("git:branch-rename", payload),
  gitCheckoutBranch: (payload) => ipcRenderer.invoke("git:branch-checkout", payload),
  gitMerge: (payload) => ipcRenderer.invoke("git:merge", payload),
  gitRebase: (payload) => ipcRenderer.invoke("git:rebase", payload),
  gitAbortRebase: (workspace) => ipcRenderer.invoke("git:rebase-abort", workspace),
  gitContinueRebase: (workspace) => ipcRenderer.invoke("git:rebase-continue", workspace),
  gitFetch: (workspace) => ipcRenderer.invoke("git:fetch", workspace),
  gitPull: (payload) => ipcRenderer.invoke("git:pull", payload),
  gitPush: (payload) => ipcRenderer.invoke("git:push", payload),
  gitRemotes: () => ipcRenderer.invoke("git:remotes"),
  gitAddRemote: (payload) => ipcRenderer.invoke("git:remote-add", payload),
  gitRemoveRemote: (payload) => ipcRenderer.invoke("git:remote-remove", payload),
  gitIsRepo: (workspace) => ipcRenderer.invoke("git:is-repo", workspace),
  gitInit: () => ipcRenderer.invoke("git:init"),
  gitLastCommitMessage: (workspace) => ipcRenderer.invoke("git:last-commit-message", workspace),
  gitCommitDetails: (hash, workspace) => ipcRenderer.invoke("git:commit-details", hash, workspace),
  gitDiffBranches: (branch1, branch2, workspace) => ipcRenderer.invoke("git:diff-branches", branch1, branch2, workspace)
});
